### ISSUE TITLE
Error on fresh install - macOS 10.12.6

### ISSUE THREAD

**Issue by BarryMode** [entdark/jaMME#13]
Installed JKA from Steam. Added jaMME 1.9 from jkhub.org to gamedata (or on a mac in this case, it's the parent folder to base).
I modified `start_jaMME.sh` to point to jaMME.

```bash
➜  ~ /Users/Anonymous/Library/Application\ Support/Steam/steamapps/common/Jedi\ Academy/SWJKJA.app/Contents/start_jaMME.sh ; exit;
LSOpenURLsWithRole() failed with error -10810 for the file /Users/Anonymous/Library/Application Support/Steam/steamapps/common/Jedi Academy/SWJKJA.app/Contents/jaMME.x86_64.app.
logout
Saving session...completed.

[Process completed]
```

That's what it returns.

Edit: I also tried it from `~/Library/Application Support/Jedi Academy`. I don't know why I thought it might make a difference, but it turned out with the same error.

**Comment by entdark** [comment]
I was actually working on a new version.
Could you tell if it works:
https://www.dropbox.com/s/yc7fwl6elqyriiw/jamme-mac.zip?dl=1
Extract everything into "/Users/Anonymous/Library/Application Support/Steam/steamapps/common/Jedi Academy" and start jamme.app.

**Comment by BarryMode** [comment]
It didn't work, but I realized I was having the same trouble with OpenJK and I didn't used to have this problem with either. I decided to start the binary directly and it gave me a different error that lead me to install SDL2 with brew. Now, I'll facing this:

```
dyld: Library not loaded: @rpath/SDL2.framework/Versions/A/SDL2
```

Which I assume means that jamme isn't seeing the path correctly. I'll let you know what I come up with.

**Comment by BarryMode** [comment]
Messed with it some more. So as I said, I installed sdl2 `brew install sdl2` and that got OpenJK working, but I'm still getting that same error for jaMME. Clearly there's a reference error of some sort. I'll post the error again, since that's still where I'm at.

```
dyld: Library not loaded: @rpath/SDL2.framework/Versions/A/SDL2
```

**Comment by BarryMode** [comment]
Hey, I think I solved this on my own. I had to get the framework manually and put it in `/library/frameworks`.

http://www.libsdl.org/download-2.0.php#source

Once I did that, I was able to execute `jamme` directly. `jamme.app` still doesn't launch, but that's ok. At least I can use it!

**Comment by entdark** [comment]
It's great that it works.

I currently want to release a new jaMME 1.11 officially for all platforms including mac.
And I want it work out of the box on mac as well.

So you are telling if I put *rd-jamme_x86_64.dylib* into *jamme.app/Contents/MacOS* then double-clicking on jamme.app starts fine?
So I can distribute it as an archive with "mme", "jamme.app" only then?

**Comment by BarryMode** [comment]
I didn't get jamme.app to ever actually launch. I am launching jamme.app/contents/macOS/jamme which worked fine with the Dylib in with it.

**Comment by entdark** [comment]
Is there any way to start jamme.app but launching the binary directly so the end users won't bother with terminal?

**Comment by BarryMode** [comment]
Yes, I got it working. Put this build folder in your gamedata and run build.sh. You may have to chmod +x on a couple files. Literally just tested this and it's good. You may also want to modify the build.sh file or move whatever around for your own personal use.

[build.zip](https://github.com/entdark/jaMME/files/1271433/build.zip)

**Comment by entdark** [comment]
@BarryMode I could not make it work with what you gave, but I could make it working with following:
`jamme`, `rd-jamme_x86_64.dylib` and `start_jaMME.command` files in GameData.
content of `start_jaMME.command` is
> cd \`dirname $0\`
> open jamme
> 
Double-clicking on that command makes jamme to start.
Could you tell if such a way works on your end?

**Comment by BarryMode** [comment]
Seems to work fine. If you need any help getting the .app to work, I think I can do that. Instead of running what I ran, it an be made much simpler than that. Anyway, as it stands, here's the built copy that I came up with that works for me:

[jaMME.app.zip](https://github.com/entdark/jaMME/files/1308763/jaMME.app.zip)

**Comment by entdark** [comment]
Why would I need to do that if I am going to distribute without .app then?
Since .app is not needed and I am not able to make it work with .app anyways.
So I will basically distribute `jamme`, `rd-jamme_x86_64.dylib`, `start_jaMME.command` and `mme` folder and it should work out of the box.
Am I missing some point?

**Comment by BarryMode** [comment]
No, there's no point if you don't see one. The .app simply is the standard for MacOS, but it doesn't really matter. Definitely not to me.
