### ISSUE TITLE
Android version 1.10 crash

### ISSUE THREAD

**Issue by elraro** [entdark/jaMME#14]
Hello. I test last version of jamme android from jkhub and i get a crash. Android 7.1

[jamme.TXT](https://github.com/entdark/jaMME/files/1493471/jamme.TXT)

**Comment by entdark** [comment]
It does not display "assets1.pk3", does that file exist?

**Comment by elraro** [comment]
Yes, the 4 files, from 0 to 3

**Comment by entdark** [comment]
For some reason the file "assets1.pk3" is not listed among other files that the game is loading:
`11-22 01:13:05.136  7153  7182 I jaMME   : Current search path:
11-22 01:13:05.136  7153  7182 I jaMME   : /storage/emulated/0/jk3/base/assets3.pk3 (16 files)
11-22 01:13:05.136  7153  7182 I jaMME   : /storage/emulated/0/jk3/base/assets2.pk3 (62 files)
11-22 01:13:05.136  7153  7182 I jaMME   : /storage/emulated/0/jk3/base/assets0.pk3 (15346 files)
11-22 01:13:05.136  7153  7182 I jaMME   : /storage/emulated/0/jk3/base`
And then it fails on loading shader files:
`11-22 01:13:06.276  7153  7182 I jaMME   : Error:
11-22 01:13:06.276  7153  7182 I jaMME   : ERROR: no shader files found
11-22 01:13:06.276  7153  7182 I jaMME   : ERROR: no shader files found`
Shader files are stored inside "assets1.pk3".
Can you check if the "assets1.pk3" file is no corrupted? And try to replace it.

**Comment by elraro** [comment]
e17ee714ce9632f401960abb1b22fa4a  assets0.pk3
3f47006dde61f171769666f31065a34c  assets1.pk3
961ad372c3cd73075d70ba71a497b89e  assets2.pk3
71c2edf5a30135d4aa921bf6259946ee  assets3.pk3

md5 of the files, can you please check it?

**Comment by entdark** [comment]
They match.
Maybe "assets1.pk3" does not have "read" permission?
Since you are on Android 7.1, check if you gave special permissions manually in the app properties.

**Comment by elraro** [comment]
Yeah, now works! :)

There is keyboard or something?

**Comment by entdark** [comment]
It's not a playable version, but it will have some minor keyboard support in the next version.
That version is designed for spectating only - just to hang around on servers.
The soft keyboard for chatting is supported, read the tutorial: https://jkhub.org/topic/6208-8-how-to-use-jamme-on-android/
